version: '3.9'

volumes:
  node-modules-vol:

networks:
  node-template-network:
    name: node-template-network

services:
  base: &base
    hostname: base
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - node-modules-vol:/home/node/app/node_modules
    networks:
      - node-template-network

  app:
    <<: *base
    hostname: app
    env_file:
      - ./.env
    ports:
      - 4444:4444
      - 9222:9222
    command: npm run dev
    restart: always
